### ISSUE TITLE
email or contac

### ISSUE THREAD

**Issue by ErikPratama** [devdreamsolution/react-responsive-infinite-card-loading#1]
can you share email or contac telephone?

**Comment by devdreamsolution** [comment]
Hi @ErikPratama , 

Let me know why you need my contact.

Best regards.

**Comment by ErikPratama** [comment]
I am very interested in your gps tracker vehicle project, I want to
ask how do I install it on a vps?

Thanks 🙏


Pada tanggal Rab, 16 Feb 2022 21.48, Devdreamsolution <
***@***.***> menulis:

**Comment by ErikPratama** [comment]
I am very interested in your gps tracker vehicle project, I want to
ask how do I install it on a vps?

Thanks 🙏

**Comment by devdreamsolution** [comment]
This is my Telegram.
https://t.me/react2node

**Comment by ErikPratama** [comment]
Thanks sir

Pada tanggal Kam, 17 Feb 2022 07.32, Devdreamsolution <
***@***.***> menulis:
